[package]
name = "dariotd_threadpool_rs"
version = "0.1.0"
edition = "2021"
description = "A simple threadpool."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
